-- MySQL Script generated by MySQL Workbench
-- 11/25/15 12:42:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema control_acceso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema control_acceso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `control_acceso` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `control_acceso` ;

-- -----------------------------------------------------
-- Table `control_acceso`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_acceso`.`alumnos` (
  `id_alumno` INT(4) NOT NULL COMMENT '',
  `dni` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `apellidos` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `foto` LONGBLOB NULL DEFAULT NULL COMMENT '',
  `tarjetaActivada` TINYINT(1) NULL COMMENT '',
  `num_tarjeta` INT NULL COMMENT '',
  `presencia` TINYINT(1) NULL COMMENT '',
  PRIMARY KEY (`id_alumno`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_acceso`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_acceso`.`asignatura` (
  `id_asignatura` INT(4) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `clave` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_asignatura`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_acceso`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_acceso`.`aula` (
  `id_aula` INT(4) NOT NULL COMMENT '',
  `numero` VARCHAR(4) NULL COMMENT '',
  `piso` VARCHAR(2) NULL COMMENT '',
  `capacidad` INT(4) NULL COMMENT '',
  PRIMARY KEY (`id_aula`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_acceso`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_acceso`.`grupo` (
  `id_grupo` INT(4) NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `tipo` ENUM('Bachiller', 'FP') NULL COMMENT '',
  `idsubgrupo` INT(11) NULL COMMENT '',
  PRIMARY KEY (`id_grupo`)  COMMENT '',
  UNIQUE INDEX `idsubgrupo_UNIQUE` (`idsubgrupo` ASC)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_acceso`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_acceso`.`profesor` (
  `id_profesor` INT(4) NOT NULL COMMENT '',
  `dni` VARCHAR(45) NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellidos` VARCHAR(45) NULL COMMENT '',
  `correo` VARCHAR(45) NULL COMMENT '',
  `contraseña` VARCHAR(45) NULL COMMENT '',
  `foto` LONGBLOB NULL COMMENT '',
  `tarjetaActivada` VARCHAR(45) NULL COMMENT '',
  `num_tarjeta` INT NULL COMMENT '',
  `presencia` TINYINT(1) NULL COMMENT '',
  `admin` TINYINT(1) NULL COMMENT 'tabla Profesor',
  PRIMARY KEY (`id_profesor`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_acceso`.`horario_profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_acceso`.`horario_profesor` (
  `id_horario_profesor` INT(4) NOT NULL COMMENT '',
  `dia_semana` ENUM('Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes') NULL COMMENT '',
  `hora_inicio` TIME(0) NULL COMMENT '',
  `hora_final` TIME(0) NULL COMMENT '',
  `id_horario_grupo` INT(4) NOT NULL COMMENT '',
  `id_profesor` INT(4) NOT NULL COMMENT '',
  PRIMARY KEY (`id_horario_profesor`)  COMMENT '',
  INDEX `fk_horarioProfesor_horarioGrupo1_idx` (`id_horario_grupo` ASC)  COMMENT '',
  INDEX `fk_horarioProfesor_profesor1_idx` (`id_profesor` ASC)  COMMENT '',
  CONSTRAINT `fk_horarioProfesor_horarioGrupo1`
    FOREIGN KEY (`id_horario_grupo`)
    REFERENCES `control_acceso`.`horario_grupo` (`id_horario_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horarioProfesor_profesor1`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `control_acceso`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_acceso`.`horario_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_acceso`.`horario_grupo` (
  `id_horario_grupo` INT(4) NOT NULL COMMENT '',
  `dia_semana` ENUM('Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes') NULL COMMENT '',
  `hora_inicio` TIME(0) NULL COMMENT '',
  `hora_final` TIME(0) NULL COMMENT '',
  `id_grupo` INT(4) NOT NULL COMMENT '',
  `id_asignatura` INT(4) NOT NULL COMMENT '',
  `id_horarioProfesor` INT(4) NOT NULL COMMENT '',
  `id_aula` INT(4) NOT NULL COMMENT '',
  PRIMARY KEY (`id_horario_grupo`)  COMMENT '',
  INDEX `fk_horarioGrupo_grupo1_idx` (`id_grupo` ASC)  COMMENT '',
  INDEX `fk_horarioGrupo_asignatura1_idx` (`id_asignatura` ASC)  COMMENT '',
  INDEX `fk_horarioGrupo_horarioProfesor1_idx` (`id_horarioProfesor` ASC)  COMMENT '',
  INDEX `fk_horarioGrupo_aula1_idx` (`id_aula` ASC)  COMMENT '',
  CONSTRAINT `fk_horarioGrupo_grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `control_acceso`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horarioGrupo_asignatura1`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `control_acceso`.`asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horarioGrupo_horarioProfesor1`
    FOREIGN KEY (`id_horarioProfesor`)
    REFERENCES `control_acceso`.`horario_profesor` (`id_horario_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horarioGrupo_aula1`
    FOREIGN KEY (`id_aula`)
    REFERENCES `control_acceso`.`aula` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_acceso`.`faltas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_acceso`.`faltas` (
  `id_faltas` INT(4) NOT NULL COMMENT '',
  `fecha` DATETIME(0) NULL COMMENT '',
  `id_alumno` INT(4) NOT NULL COMMENT '',
  `id_horarioGrupo` INT(4) NOT NULL COMMENT '',
  `observaciones` VARCHAR(300) NULL COMMENT '',
  PRIMARY KEY (`id_faltas`)  COMMENT '',
  INDEX `fk_faltas_alumnos1_idx` (`id_alumno` ASC)  COMMENT '',
  INDEX `fk_faltas_horarioGrupo1_idx` (`id_horarioGrupo` ASC)  COMMENT '',
  CONSTRAINT `fk_faltas_alumnos1`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `control_acceso`.`alumnos` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_faltas_horarioGrupo1`
    FOREIGN KEY (`id_horarioGrupo`)
    REFERENCES `control_acceso`.`horario_grupo` (`id_horario_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_acceso`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_acceso`.`matricula` (
  `id_matricula` INT(4) NOT NULL COMMENT '',
  `id_alumno` INT(4) NOT NULL COMMENT '',
  `id_asignatura` INT(4) NOT NULL COMMENT '',
  PRIMARY KEY (`id_alumno`, `id_asignatura`, `id_matricula`)  COMMENT '',
  INDEX `fk_alumnos_has_asignatura_asignatura1_idx` (`id_asignatura` ASC)  COMMENT '',
  INDEX `fk_alumnos_has_asignatura_alumnos_idx` (`id_alumno` ASC)  COMMENT '',
  CONSTRAINT `fk_alumnos_has_asignatura_alumnos`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `control_acceso`.`alumnos` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_has_asignatura_asignatura1`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `control_acceso`.`asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_acceso`.`alumno_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_acceso`.`alumno_grupos` (
  `id_alumno_grupos` INT(4) NOT NULL COMMENT '',
  `id_alumno` INT(4) NOT NULL COMMENT '',
  `id_grupo` INT(4) NOT NULL COMMENT '',
  PRIMARY KEY (`id_alumno_grupos`, `id_alumno`, `id_grupo`)  COMMENT '',
  INDEX `fk_alumnos_has_grupo_grupo1_idx` (`id_grupo` ASC)  COMMENT '',
  INDEX `fk_alumnos_has_grupo_alumnos1_idx` (`id_alumno` ASC)  COMMENT '',
  CONSTRAINT `fk_alumnos_has_grupo_alumnos1`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `control_acceso`.`alumnos` (`id_alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_has_grupo_grupo1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `control_acceso`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `control_acceso`.`profesor_asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_acceso`.`profesor_asignatura` (
  `id_profesor_asignatura` INT(4) NOT NULL COMMENT '',
  `id_asignatura` INT(4) NOT NULL COMMENT '',
  `id_profesor` INT(4) NOT NULL COMMENT '',
  PRIMARY KEY (`id_asignatura`, `id_profesor`, `id_profesor_asignatura`)  COMMENT '',
  INDEX `fk_asignatura_has_profesor_profesor1_idx` (`id_profesor` ASC)  COMMENT '',
  INDEX `fk_asignatura_has_profesor_asignatura1_idx` (`id_asignatura` ASC)  COMMENT '',
  CONSTRAINT `fk_asignatura_has_profesor_asignatura1`
    FOREIGN KEY (`id_asignatura`)
    REFERENCES `control_acceso`.`asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignatura_has_profesor_profesor1`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `control_acceso`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
